import test from 'node:test';
import assert from 'node:assert/strict';
import {OcclusionTracker,bodyPosition,type Point} from '../src/core/pose';
function pose():Point[]{const p=Array.from({length:33},()=>({x:.5,y:.5,visibility:1}));p[11]={x:.35,y:.2,visibility:1};p[12]={x:.65,y:.2,visibility:1};p[23]={x:.4,y:.8,visibility:1};p[24]={x:.6,y:.8,visibility:1};p[15]={x:.4,y:.5,visibility:1};p[16]={x:.6,y:.5,visibility:1};return p;}
test('one hidden wrist follows visible wrist with saved basket offset on either side',()=>{for(const hidden of [15,16]){const t=new OcclusionTracker(),p=pose();const initial=t.update(p,0)!;p[hidden].visibility=.1;const visible=hidden===15?16:15;p[visible].x+=.12;p[visible].y+=.06;const inferred=t.update(p,100)!;assert.equal(inferred.quality,'single');assert.ok(Math.abs(inferred.x-(initial.x-.2))<1e-6);assert.ok(Math.abs(inferred.y-(initial.y+.1))<1e-6);assert.equal(t.update(p,2001),null);}});
test('single wrist is never sufficient before seeing both hands',()=>{const p=pose();p[15].visibility=.1;assert.equal(new OcclusionTracker().update(p,0),null);});
test('both lost hands bridge only a brief gap; lost torso cancels immediately',()=>{const t=new OcclusionTracker(),p=pose();t.update(p,0);p[15].visibility=0;p[16].visibility=0;assert.equal(t.update(p,300)?.quality,'held');assert.equal(t.update(p,351),null);const q=pose();t.update(q,1000);q[23].visibility=0;assert.equal(t.update(q,1100),null);q[23].visibility=1;q[15].visibility=0;assert.equal(t.update(q,1200),null);});
test('reacquired wrists refresh offsets; camera reset discards old person',()=>{const t=new OcclusionTracker(),p=pose();t.update(p,0);p[15].visibility=0;t.update(p,1900);p[15].visibility=1;assert.equal(t.update(p,2000)?.quality,'both');p[15].visibility=0;assert.equal(t.update(p,3900)?.quality,'single');t.reset();assert.equal(t.update(p,4000),null);});
test('hidden elbow does not veto visible hands and torso',()=>{const p=pose();p[13].visibility=0;p[14].visibility=0;assert.equal(bodyPosition(p)?.quality,'both');});
